{% set name = "sparselt" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LiamBindle/sparselt/archive/{{ version }}.tar.gz
  sha256: 76ed9f616e0247cddeb1490a6f98d20028db3d9e2822824037bfde23a086034d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - netcdf4
    - numpy
    - python
    - scipy
    - xarray

test:
  imports:
    - sparselt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LiamBindle/sparselt
  license: MIT
  license_file: LICENSE
  summary: A small library for regridding Earth system data with vectorized sparse linear transforms.

extra:
  recipe-maintainers:
    - LiamBindle
